### ISSUE TITLE
enable issue tracking on the LTG Oslo repository

### ISSUE THREAD

**Issue by oepen** [akutuzov/simple_elmo#3]
is it because the version hosted in the LTG Oslo organization is a fork of this one, or is it just a switch in M$ GitHub somewhere: i appear unable to create tickets on the LTG Oslo version of this repository.  i expect that version (rather than this personal one) should become the primary home of this code, or?

**Comment by akutuzov** [comment]
Yes, I definitely plan to make the version at the LTG Oslo repository the primary one.
Will do that as soon as possible.
